### ISSUE TITLE
Bug: On some Android Devices there might be issues initiating dropdowns

### ISSUE THREAD

**Issue by pjdohertygis** [pjdohertygis/SARandFirstResponderSurvey#1]
While at the FEMA USAR meeting, one member of NY-TF1 had issues getting the dropdown to load for waypoints. He is going to send me a note with the exact model and OS.

**Comment by pjdohertygis** [comment]
@pjdohertygis I will send a note to follow up right now.

**Comment by tedrick** [comment]
@pjdohertygis - it would be quite helpful to know what type of Android device is present.  The dropdown for waypoints isn't terribly large; that being said, one of areas the 64-bit release of Survey123 Android (which occurred over the summer) shows significant improvement in is in working with choice lists.

**Comment by pjdohertygis** [comment]
@tedrick - Timothy just replied so I will close this out.

"Good Afternoon Paul, 

I have not seen that issue persist.  Currently all NY-TF1 devices are Apple products, though some members personal devices are Android.  Personally I use a Pixel 2 and have not experienced this problem.

Take care and enjoy,
Tim"
________________________________________
