### ISSUE TITLE
Enhancement: Hidden field for upload time from GPS

### ISSUE THREAD

**Issue by pjdohertygis** [pjdohertygis/SARandFirstResponderSurvey#14]
@jdokemaps came across this while helping with the gpx uploader.

**Comment by pjdohertygis** [comment]
Check with the Ironsites process to make sure it is compatible.

**Comment by jdokemaps** [comment]
The database has four date fields in it: Start_time, end-time, CreationDate, and EditDate.

start_time is when the survey was started. This is filled out in Survey123 and QuickCapture. It is Null when data is created in the Editing App. This is the field that I recommend using for the GPS time when appending data collected by a GPS.

end_time is filled out by Survey123. When QuickCapture is used, the field is filled in with "1/1/1900" . This field would be blank if data was appended using GPS data or data is created in the Editing App.
 
CreationDate is when the data enters the database. If you uploaded data from a GPS. the Start_time would have the date and time the data was collected on the GPS and the CreationDate would have the date and time the data was actually entered into the database.

EditDate is when that point was edited in any way. This is where you can see the time the point was last edited. 

Thoughts @pjdohertygis

**Comment by pjdohertygis** [comment]
I think this works, just need to keep this in mind for any Iron Sites documentation, etc.
