### ISSUE TITLE
Enhancement: Lifelines Guidance Doc

### ISSUE THREAD

**Issue by pjdohertygis** [pjdohertygis/SARandFirstResponderSurvey#15]
Laura Silsbee and Harris Henbest have been working on a doc.
Harris_Henbest@sheriff.org
laura.silsbee@tntf1.org
![image](https://user-images.githubusercontent.com/4256979/64361417-5e586580-cfc1-11e9-9aa4-f0da5fec84b0.png)

**Comment by pjdohertygis** [comment]
Request started with Capt Mike Parker CO-TF1 

"Hi Paul,

Would it be possible to add some type of info page or link about Community Lifelines into Survey123? The idea is that there would be a quick way, within the app, to review details or examples about Lifelines so that the correct choice could be made in a survey. 

We plan to do separate training about the Lifelines, but an in-app reference would be nice.

Cheers,
Mike

Mike Parker
Training Manager
Colorado Task Force 1
FEMA Urban Search and Rescue
Captain, West Metro Fire Rescue
3535 S. Kipling Parkway
Lakewood, CO 80235-1201
mparker@westmetrofire.org

**Comment by pjdohertygis** [comment]
Host a graphic in ArcGIS Online and link to it. See example from above and reach out to Laura.

**Comment by jdokemaps** [comment]
I reached out to Laura and Harris to see what they had. 

For now, I added a link in the hint section of the Community Lifeline question that links to the above image which is saved in the NAPSG AGOL. 

![image](https://user-images.githubusercontent.com/52461518/70279865-8bf5ac00-1774-11ea-8090-cef2629e8243.png)

**Comment by dweber-mo** [comment]
Having a link to this relatively new directive from the app is a great idea.

**Comment by jdokemaps** [comment]
Going to update new lifelines icons.
