### ISSUE TITLE
Enhancement: Remove repeat and related table for Victim Details

### ISSUE THREAD

**Issue by pjdohertygis** [pjdohertygis/SARandFirstResponderSurvey#16]
The victim details/patient identification has not been widely used by agencies and also produces a potential roadblock to sharing the data since it is more likely to contain PII.

It is also producing a technical challenge with producing multiple forms for one feature layer. 

For R&D, I'd like us to test if we can eliminate this repeat / related table without breaking an existing Survey. This would make it easier to transition users between V6 and V7.

**Comment by pjdohertygis** [comment]
@tedrick if we remove this from existing surveys - will it be a "breaking change"? We are not worried about losing data, just want to make sure if we need to kill this related table, everything would be OK with the service and form.

**Comment by pjdohertygis** [comment]
I am testing this out right now. I published a v7 prototype with the repeat in. Then I went into the XLSForm and deleted the rows for repeats. So far, this did not break the Survey.

**Comment by tedrick** [comment]
@pjdohertygis - removing a repeat from form is not a change the results in republishing the feature service.

**Comment by jdokemaps** [comment]
The repeat is gone in v7
