### ISSUE TITLE
Enhancement:  Add Field MGRS

### ISSUE THREAD

**Issue by kthenson** [pjdohertygis/SARandFirstResponderSurvey#18]
Can we look at having a new field that collects the MGRS coordinates when a location is selected?  Much like the USNG field, we have a need to get the MGRS coordinate.  Our state, as well as several others, utilize a helicopter aquatic rescue team that is comprised of military and civilian assets.  Our HART pilots rely on MGRS coordinates to coordinate their missions.

**Comment by pjdohertygis** [comment]
@kthenson Good point, but MGRS is already included in the data schema and is equivalent to taking the spaces out of USNG. We will try to make this more clear in the future!
