### ISSUE TITLE
Enhancement: Deploy symbology across all feature layer views?

### ISSUE THREAD

**Issue by pjdohertygis** [pjdohertygis/SARandFirstResponderSurvey#20]
Is there any potential for Esri to build a tool for pushing symbology across all feature layer views systematically? 

The issue we have is the symbology not showing in the stakeholder view, which means it does not show up on the back-end of Survey123 Data Tab, which also means when people download the KML (this is still relevant for SAR), the data does not have any symbology. 

It takes about 10-15 minutes each time for us to change the symbology because there +24 icons. For novice users, it would take much longer.

**Comment by IsmaelInRedlands** [comment]
Hi Paul. I think this should be brought up to the ArcGIS Online team. There may be a tool available already. Did you try asking Kelly Gerrow?

**Comment by pjdohertygis** [comment]
See post here and monitor https://community.esri.com/thread/244232-what-is-the-best-practice-for-symbolizing-survey123-feature-layers-views#.XeaYkGtcRlY.twitter

Let's try GeoJobe tool again? https://www.geo-jobe.com/admintooltips/video-arcgis-copy-symbology/

**Comment by adf102** [comment]
Something interesting I noticed is that the SAR V6 Sandbox back-end has the symbols on the Data page, but I tried looking at other examples and a V7 test Jared made and they still show as red dots. I wonder what makes the V6 Sandbox different that allows this?
![image](https://user-images.githubusercontent.com/55416740/70577107-1fadea80-1b70-11ea-9f5b-7b4d0bf43f7d.png)

**Comment by pjdohertygis** [comment]
@adf102 I updated the stakeholder view in v6 manually, but I am hoping to find a way to semi-automate this by copying from the Master to the stakeholder view.

**Comment by jdokemaps** [comment]
Hoping Esri will implement this in the future.
