### ISSUE TITLE
Bug: Weak wifi connection forcing a login

### ISSUE THREAD

**Issue by pjdohertygis** [pjdohertygis/SARandFirstResponderSurvey#21]
- Survey123 Mobile App (downloaded in the last few days)
- iPad Mini 5th Generation (CATF6 Cache - point of contact Jonathan jglassman@exponent.com and Billy WMilligan@riversideca.gov

Today during training they were testing going offline / airplane mode and then connecting to their mobile wifi kit. 
Over a weak wifi connection, they were getting forced to log-in. If they did not find a stronger wi-fi connection the app just froze and would not go to the log-in page.  Once they move closer to the wi-fi source, they could sign-in, but the problem is why were they getting logged out in the first place. 

*Similar problem with QuickCapture logging and / or the Send button being disabled. The resolution for QC was to kill the app, then log back in with a better connection. I posted on the Early Adopter Forum, see  "Working Offline - Then Connecting to Wifi - Data won't send"

@IsmaelInRedlands I know these may not be bugs and just known limitations but I am adding you for awareness. Let me know if you need more information. 

@jdokemaps just FYSA

**Comment by pjdohertygis** [comment]
From @IsmaelInRedlands - this is being addressed in the next update and we will test with CATF6 

"During the 8th Western Division Meeting a few weeks back, some of the testers run into issues when attempting to submit data from Survey123. Apparently, the app was not working well against the WIFI that was setup for the field exercise and caused the ‘circle of death’ to appear.  We have been working on this issue, which also was causing people to be logged-out randomly, and we believe we have a fix."

**Comment by IsmaelInRedlands** [comment]
@pjdohertygis   Just FYI. We have tentatively added a field test with Jonathan in Riverside on Dec 6  to give the fix a go. We are waiting on confirmation from the coms team.

**Comment by pjdohertygis** [comment]
@IsmaelInRedlands - RE: weak connection forcing login - do you think I can close this issue for Survey123? I know they are still working on it for QuickCapture but want to give an update on Survey123 and what they should expect?

**Comment by IsmaelInRedlands** [comment]
This should no longer be an issue in Survey123. I think we should close and reopen if you see it again.
For QuickCapture, the fix should come on Dec 6 2020.  The Beta builds should already address this.

**Comment by pjdohertygis** [comment]
AWESOME! Thank you @IsmaelInRedlands
