### ISSUE TITLE
Bug: iOS Crash

### ISSUE THREAD

**Issue by jdokemaps** [pjdohertygis/SARandFirstResponderSurvey#22]
IOS 13 if accessing the folder for photos it crashes.

**Comment by pjdohertygis** [comment]
@IsmaelInRedlands is this a known issue? Do you need more information?

**Comment by IsmaelInRedlands** [comment]
Whats the build number of Survey123?
If you download the latest build from the store (3.6), the crash should not occur.
https://support.esri.com/en/bugs/nimbus/QlVHLTAwMDEyNTI5NQ==

**Comment by pjdohertygis** [comment]
I'll try to find out more details but this was posted on Sept 20th so likely before the 3.6. I'll close it now and re-open if it pops up again.
