### ISSUE TITLE
Enhancement: Hide Search Type from the Survey123 Form

### ISSUE THREAD

**Issue by pjdohertygis** [pjdohertygis/SARandFirstResponderSurvey#23]
We put this field into the schema to be compatible with outputs from Iron Sights, but it is not needed at the point of entry for Survey123 waypoints. It could be potentially confusing.

**Comment by jdokemaps** [comment]
How do you add that information in on the backend then? I think it will make more work for the GISS/TIS later on and add even more confusion. There needs to be a way to track what type of search was conducted (which gives you an estimate of how well an area was covered).

**Comment by pjdohertygis** [comment]
No one really understood why it needs to be in their at the point level - on the tracks yes but not sure it needs to be there at the waypoint level. Let’s consult the USARWG and Bubba/Plans.

**Comment by pjdohertygis** [comment]
Bubba from CATF1 - Yes. This needs to remain. The documentation of the Mission Type is a critical piece of information that documents why each team did or did not do something while searching. The Mission Type also has an impact on the types Icons that may be used.

**Comment by pjdohertygis** [comment]
Overruled
