### ISSUE TITLE
Enhancement: Do we really need the instructions for Drafts? Would just using Favorites work? 

### ISSUE THREAD

**Issue by pjdohertygis** [pjdohertygis/SARandFirstResponderSurvey#24]
Favorites vs. Drafts is confusing, we need to work out an easy way to explain it. Do we really need Drafts?

**Comment by tedrick** [comment]
As I noted to @jdokemaps , I took the feedback from his training regarding favorites/drafts and have taken it back to the Survey123 team to consider improving in the future.  

Favorites currently works on an entire survey, not just the questions filled out at the time 'Save to Favorites' is pressed.  If you want to have a partially filled in form, the technique you are currently using (saving the partial form to drafts) is probably the best.

**Comment by pjdohertygis** [comment]
We will keep this as-is for now and wait for Survey123 Team to incorporate feedback.
