### ISSUE TITLE
Change Image Size to Unrestricted

### ISSUE THREAD

**Issue by eshreveazdema** [pjdohertygis/SARandFirstResponderSurvey#28]
The current Survey should have an unrestricted limit for the image size when taking a photo. I am opening up some of the photos on the training Survey and the photos appear to be fairly small.

**Comment by pjdohertygis** [comment]
@eshreveazdema - do you think we could find a middle ground on size? We don't want the images to be too large, otherwise, it could impact performance over low bandwidth connections. Have you done any R&D on this?

**Comment by eshreveazdema** [comment]
@pjdohertygis that would be fine. I think anything better than the default pixel option would best for all parties. When you do an export of the jpeg from S123 or a Dashboard the images are extremely small.

**Comment by pjdohertygis** [comment]
@tedrick If we end up with 100,000 points in a Survey123 database, with ~30% having photos.... What would be a good best practice for photo size? Keep in mind we want to stay in an ArcGIS Online environment without moving to the premium data store, etc. 

What size would you recommend?

![image](https://user-images.githubusercontent.com/4256979/69483648-afb50b80-0dde-11ea-9695-9cb4be0e8816.png)

**Comment by tedrick** [comment]
We normally don't recommend specific sizes; if the current pictures are too small, you should certainly increase it. 1920 pixels is the same as an HD screen and is thus likely to be the largest most monitors could show.

**Comment by jdokemaps** [comment]
We went with 1920 pixels.
