### ISSUE TITLE
Enhancement: Add a field for site sketch

### ISSUE THREAD

**Issue by pjdohertygis** [pjdohertygis/SARandFirstResponderSurvey#29]
Ask Ismael for details, see an example from INSARAG Forms. 

Doc: https://community.esri.com/groups/survey123/blog/2017/10/09/smart-skething-in-survey123-stroke-by-stroke

**Comment by pjdohertygis** [comment]
Here is how to do it 
![image](https://user-images.githubusercontent.com/4256979/70097308-ef010a80-15dd-11ea-8aac-c79d850e80fb.png)

**Comment by pjdohertygis** [comment]
Question: Do we want to annotate on photos? Or add a blank canvas? Or both?

**Comment by jdokemaps** [comment]
I added the ability to annotate on all three photos. 
![image](https://user-images.githubusercontent.com/52461518/70298453-f297bb80-17ae-11ea-895c-677e72655b9a.png)

**Comment by pjdohertygis** [comment]
Problem(s): 

1. When I take a landscape photo and annotate it, it gets uploaded as a portrait making it very small.
2. The interface for the end-user adds extra steps that are unfamiliar to existing users. 
3. Notice the dimensions are smaller than 1920px even though 1920 was the setting chosen in Survey123 Connect.

Recommendation: I recommend disabling the annotate capability on the image until we get this figured out. OR add a separate image question just for sketching? 

Example using landscape photo
![image](https://user-images.githubusercontent.com/4256979/70483424-32a3ba80-1a9d-11ea-99f6-879e12c9a8d1.png)

Example using portrait photo
![image](https://user-images.githubusercontent.com/4256979/70483444-40594000-1a9d-11ea-9dd1-ba64d267f394.png)

**Comment by tedrick** [comment]
On the issues above:
1.  The photo is being added to the annotate canvas 'right-side-up'; they can be rotated through the menu controls:
<img src="https://user-images.githubusercontent.com/1319289/70738960-a5de4400-1cca-11ea-8b3f-237843d3b82e.PNG" height="350" />
2. Could you describe the extra steps that are a concern?
3. The image size is not based on the camera; it is based on the screen size of the device (to account for the drawing that is being done).

**Comment by pjdohertygis** [comment]
@tedrick but... then the photo looks like this in attachments : ( 
![image](https://user-images.githubusercontent.com/4256979/71126693-5a320b80-219e-11ea-8667-12c7ddcd5c58.png)

**Comment by tedrick** [comment]
Reasonable point - I've noted the lack of rotation.

**Comment by jdokemaps** [comment]
We are going to have photos only for now. We may come back to this in future versions.
