### ISSUE TITLE
What is the optimal Inbox configuration?

### ISSUE THREAD

**Issue by pjdohertygis** [pjdohertygis/SARandFirstResponderSurvey#33]
What would be the ideal setup for the inbox?
USNG
Waypoint type
Comments (might be too long?)
Follow-up Status

**Comment by pjdohertygis** [comment]
See Ismael's comments on making Follow-up color-coded. https://github.com/pjdohertygis/SARandFirstResponderSurvey/issues/19

**Comment by pjdohertygis** [comment]
@jdokemaps - Based on feedback from the exercise on 1/28/20 with SCTF1

- Filter the Survey123 Inbox to show only needs follow-up, assigned (you can still see Completed, No Follow-up Needed in the web map.
- Make assignments a yellow/orange color (unless it is too hard to read)

**Comment by pjdohertygis** [comment]
Looking good! 
![image](https://user-images.githubusercontent.com/4256979/73891823-f5a03e00-4829-11ea-88a9-71a01953e62b.png) 
![image](https://user-images.githubusercontent.com/4256979/73891836-005ad300-482a-11ea-906f-2c3c913c42bb.png)

**Comment by jdokemaps** [comment]
Implemented color changes and a filter for Needs Followup and Assigned. If you want to clear this filter, it must be done in the xls form when publishing.
