### ISSUE TITLE
Lifeline Questions only for Structure Surveys (4 categories), Hazards, Route Blocked?

### ISSUE THREAD

**Issue by pjdohertygis** [pjdohertygis/SARandFirstResponderSurvey#34]
It seems unnecessary to always have the Lifelines question open. The purpose was to indicate when a structure/infrastructure survey is related to one of the 7 Lifelines, so let's try making it only show when it is structure related.

**Comment by HHenbest** [comment]
Less is more, Lifeline questions should only pop up with structure related damage

**Comment by dweber-mo** [comment]
I agree that it could be pared down but on first blush, it seems like a number of "non-people" waypoints may relate to lifelines e.g. hazmat, route blocked, other hazard, helicopter LZ, flood/water level, etc.

**Comment by HHenbest** [comment]
I don’t disagree, I think we can safely leave all that specific to community lifelines in place and take a look at the volume and accuracy of the usage for this coming hurricane season and review it then

Harris Henbest

**Comment by pjdohertygis** [comment]
This is a duplicate with https://github.com/pjdohertygis/SARandFirstResponderSurvey/issues/32 - @jdokemaps is working on this today

**Comment by pjdohertygis** [comment]
Solution is...  ${waypoint_cat_cal}!='Human Interaction'
