### ISSUE TITLE
Question: Should we simplify the PDA Questions? 

### ISSUE THREAD

**Issue by pjdohertygis** [pjdohertygis/SARandFirstResponderSurvey#35]
Jared and Paul to add more details - essentially should we simplify the damage survey follow up questions to be simply (Needs PA Follow-up, Needs IA Follow-up, etc).

**Comment by HHenbest** [comment]
the less words operators have to read on the screen of a phone or tablet, the better

**Comment by dweber-mo** [comment]
I agree with HHenbest.  In the 123 app, the shorter the better.

**Comment by jdokemaps** [comment]
We will revisit this in future versions.
