### ISSUE TITLE
Add Degree Decimal Minutes as a field, using pull data

### ISSUE THREAD

**Issue by pjdohertygis** [pjdohertygis/SARandFirstResponderSurvey#36]
This is the aviation standard and it is a good idea to stamp the data with it.

**Comment by adf102** [comment]
I took the same template at the USNG note and tried to do the same thing with this. Any ideas why this is the output here?
![image](https://user-images.githubusercontent.com/55416740/70295971-861cbc80-17ae-11ea-81e0-1d50e44b96c3.png)

**Comment by pjdohertygis** [comment]
@tedrick any ideas on the above?

**Comment by jdokemaps** [comment]
@adf102 I believe you have to specify which parameters you want to extract. This is what I currently have: pulldata("@geopoint",${location},"DDM.latitudeText") + "  " + pulldata("@geopoint",${location},"DDM.longitudeText")   Is this the simlest way to do it @tedrick ?

**Comment by tedrick** [comment]
The "Map Coordinates" sample in Survey123 Connect should provide guidance on this, as does the [Survey123 Help](https://doc.arcgis.com/en/survey123/desktop/create-surveys/geopoints.htm#ESRI_SECTION1_0C78C5A67E824AC9A4EB47693D47D151).  The syntax for DDM text overall is:
`pulldata("@geopoint",${location},"DDM.text")`

you can use `pulldata("@GeoPoint",${location},"DDM.latitudeText")` /  `pulldata("@GeoPoint",${location},"DDM.longitudeText")` for the lat/long
