### ISSUE TITLE
Basemap issues with 3.7.56 - Standard (Beta) Map

### ISSUE THREAD

**Issue by pjdohertygis** [pjdohertygis/SARandFirstResponderSurvey#37]
Settings: Basemap set to Community Topographic (Map service based?). 

This is on our current prototype tv7a SAR Survey (and others) published with Survey123 Connect 3.7.6.

Android Pixel Version 10, Survey123 3.7.56 - there appears to be transparency or missing layer in the World Topographic. The building footprints and roads show up, but not the other features.
![image](https://user-images.githubusercontent.com/4256979/70345531-25729b80-1811-11ea-81fd-9f5b031bede3.png)

iPhone 11: Looking good
![image](https://user-images.githubusercontent.com/4256979/70345491-0ecc4480-1811-11ea-9cf1-bc5b1de4d461.png)

@tedrick @IsmaelInRedlands have you seen any issues like this? 

Also... is there a way to load the vector tile basemaps vs. map service-based one?

**Comment by pjdohertygis** [comment]
Update: once I switched my settings on iPhone 11 to Map Standard "Beta" - I was able to replicate.

**Comment by tedrick** [comment]
@pjdohertygis - The map that shows without a background appears to be the Vector Tiled version of the Community Basemap; the one in the Basic Maps is a map service.  What's occurring is that the hillshade layer underneath the web map is not displaying.  We will address this as part of finalizing the Standard map types out of beta.

**Comment by pjdohertygis** [comment]
Ok awesome and thank you!!!
