### ISSUE TITLE
Is there a way to assign a default order to the features for symbology?

### ISSUE THREAD

**Issue by jdokemaps** [pjdohertygis/SARandFirstResponderSurvey#38]
@tedrick After the survey is published, we go to set the symbology for the Master feature layer and the waypoints are not in the order in which they are in the choices list in the xlsx doc. Is there a way to assign a default order so that we don't have to keep re-ordering them?
![image](https://user-images.githubusercontent.com/52461518/70363639-6cc74f00-1846-11ea-866e-fc1435011b6c.png)

**Comment by tedrick** [comment]
You're able to revise the order in the symbology editor of the map viewer.
