### ISSUE TITLE
Show MGRS on the Survey? 

### ISSUE THREAD

**Issue by pjdohertygis** [pjdohertygis/SARandFirstResponderSurvey#39]
Request from Chad Beam - show the MGRS field for HART (helo) teams.

**Comment by epratt5** [comment]
I think it would be good to have the options for USNG and MGRS.

**Comment by HHenbest** [comment]
Yes please, the options for MGRS and USNG are helpful.

**Comment by pjdohertygis** [comment]
USNG is functionally the same as MGRS, it just has spaces. However, since the military brings the helicopters.... "The customer is always right". Implemented.
