### ISSUE TITLE
Web Form does not keep exact details of Survey when editing

### ISSUE THREAD

**Issue by pjdohertygis** [pjdohertygis/SARandFirstResponderSurvey#41]
Team - we are trying to make it as easy as possible to edit a specific web form using the Survey123 Web Form. 

We want the end-user to be able to click on a link in Operations Dashboard or web map popup and quickly edit the Survey using the Survey123 Web Form. 

Example: 
![image](https://user-images.githubusercontent.com/4256979/71132180-a9cb0400-21ab-11ea-90ea-f12daa4a9645.png)

Clicking this link unfurls the following URL https://survey123.arcgis.com/share/924c450187014beea32918d6d8a57662?mode=edit&objectId=278

This is AWESOME! Because I can simply update the Follow-Up to Assigned, and Assign it to someone. But notice one small, but very critical error. The Survey originally stated 3 people, but now it says 1 person (the default). It stays three if I open it in the Survey123 Field App, Web Map, or Web App.

![image](https://user-images.githubusercontent.com/4256979/71132341-05958d00-21ac-11ea-9efd-5d79820a8342.png)

Is there a short-term fix we can make? 
Is this documented as a bug/enhancement for longer-term?

**Comment by IsmaelInRedlands** [comment]
It looks as if the default value (or a calculation) is overwriting the value in that attribute.
This definitively needs a closer look on our end.
Could you please open an Esri Technical Support case for this?

**Comment by pjdohertygis** [comment]
Ok yes, I think the default is indeed 1. Confirming, no problem with Survey123 Field App, just the web form. I'll try catching support now to get it started.

**Comment by pjdohertygis** [comment]
Esri Case #02462213 - they will send this to Field Apps Team to close the loop.

**Comment by pjdohertygis** [comment]
Update: I think this issue (or related issue) is showing up in the Survey123 Inbox now as well - right around this point in the video https://youtu.be/xECj1TyLxlI?t=486 

When we change the dropdown to a new waypoint type, it automatically resets the victim count to one. Perhaps we should simply get rid of the default value for this field? The challenge here is, we run the risk of someone entering a new waypoint for a human interaction, but not indicating the number of people.

**Comment by tedrick** [comment]
@pjdohertygis - with regard to the field app, to confirm you are talking about the `victim_num` question, correct? 

That question has a calculation (not a default value) and is also relevant based on the same field as it uses the calculation, so it appears designed to 'reset' if Human Interaction is selected.  If you change category from 'Human Interaction', `victim_num` is no longer relevant and its value is nulled out.  If you reselect 'Human Interaction', it becomes relevant again and then is calculated to 1.

**Comment by pjdohertygis** [comment]
@jdokemaps we will have to revisit this and tinker with the XLSForm. 

@tedrick so then is Esri Case #02462213 likely NOT a bug? Just a configuration challenge?

**Comment by tedrick** [comment]
It's possible depending on what specific editing you were doing (the web app and field app have different processing engines, so it isn't guaranteed).  That is something the Support Analyst should help you work through - if they have questions, let them know they should feel free to reach out to us.

**Comment by pjdohertygis** [comment]
Ok this has been logged! 

BUG-000127719 - When Survey 123 webform is launched in edit mode, a calculation overwrites the existing value

**Comment by pjdohertygis** [comment]
@tedrick is this bug now fixed? If so we will close this issue.

**Comment by pjdohertygis** [comment]
@tedrick disregard I can see it is still open! 
![image](https://user-images.githubusercontent.com/4256979/75359280-0c561580-5869-11ea-94e1-70d9fd101feb.png)

**Comment by pjdohertygis** [comment]
This bug has been squashed!
