### ISSUE TITLE
Optimal Scale of Map in Survey123 Field App

### ISSUE THREAD

**Issue by pjdohertygis** [pjdohertygis/SARandFirstResponderSurvey#43]
I am submitting this on behalf of Pete Hanna.

"Scale of the location map for one. Should be closer when you open it. Especially if you are doing damage assessment"

Question for the WG - what should the scale be when you open the Survey123 Field App?

**Comment by pjdohertygis** [comment]
Keep in mind there is a Preview Map and Detailed Map. This is what the interface looks like in Survey123 Connect when you set it up. 

![image](https://user-images.githubusercontent.com/4256979/71291002-2550c080-2326-11ea-9436-c482f6ab3d28.png)

**Comment by HHenbest** [comment]
No preference on scale when opening the app, ill zoom into what's needed.

**Comment by dweber-mo** [comment]
My preference would be about 500m or a couple of city blocks for 123.  Dashboards should be about a state or about 500km.

**Comment by jdokemaps** [comment]
I set the Preview Map zoom level to 0 and the Detailed Map to Zoom level 19.
