### ISSUE TITLE
Workflow issues for Submitting survey via webform in Dashboard

### ISSUE THREAD

**Issue by jdokemaps** [pjdohertygis/SARandFirstResponderSurvey#44]
After you submit a survey via the webform in the dashboard, you can't submit another survey without refreshing. Look into adding a link to submit another survey (although I think this is only available via publishing the survey via the web).
![image](https://user-images.githubusercontent.com/52461518/71741719-d7a38000-2e1c-11ea-8a84-d5dbc93d5e90.png)

Another solution would be to embed a link to the survey in the dashboard which would open the survey form in another tab.

**Comment by pjdohertygis** [comment]
I agree we may want to think about adding a dropdown for when a Survey is creating from the ICP (or somewhere other than the field). 

In the meantime, I've gotten rid of the embedded form and add a link at the bottom of the Dashboard.
