### ISSUE TITLE
Enhancement: Horizontal Accuracy field should be numeric

### ISSUE THREAD

**Issue by pjdohertygis** [pjdohertygis/SARandFirstResponderSurvey#5]
See this tweet for more context. https://twitter.com/esriSurvey123/status/1146063052472647681

"You can control decimals shown by formatting the field display in the popup.  If using Connect, you can also use the round() function to limit the number of decimals stored."
![image](https://user-images.githubusercontent.com/4256979/60521464-2c164900-9c9c-11e9-8e31-f3479a0a9e3e.png)

**Comment by IsmaelInRedlands** [comment]
Please note that hidden questions are by default persisted as text fields, but you can overwrite that behavior using the bind::esriFieldType column.

**Comment by jdokemaps** [comment]
I made the field type "esriFieldTypeSingle"
![image](https://user-images.githubusercontent.com/52461518/70264986-bb95bb80-1756-11ea-8ce3-c4355e300428.png)

**Comment by IsmaelInRedlands** [comment]
If using an integer field, make sure you cast the horizontal accuracy to an integer. Otherwise you will get error when trying to insert a double into an integer.  @jdokemaps

**Comment by jdokemaps** [comment]
Thank you @IsmaelInRedlands ! Changed to Integer
![image](https://user-images.githubusercontent.com/52461518/70270758-4def8c80-1762-11ea-9e55-480c20fc15fa.png)
