### ISSUE TITLE
Add Waypoint for HR Victim Detected

### ISSUE THREAD

**Issue by jdokemaps** [pjdohertygis/SARandFirstResponderSurvey#53]
Suggestion from Katie Breland with TX-TF1:
Since there are live-find and HR dogs, add a waypoint for HR Victim Detected.

**Comment by pjdohertygis** [comment]
Also see https://github.com/pjdohertygis/SARandFirstResponderSurvey/issues/56

**Comment by pjdohertygis** [comment]
Closing since it is a duplicate - see #56
