### ISSUE TITLE
Tracklines - reduce thickness of lines, especially targeted search

### ISSUE THREAD

**Issue by pjdohertygis** [pjdohertygis/SARandFirstResponderSurvey#58]
"Another item that I found a little off was the thickness variation of the Tracklogs.  Was there a reason to have thickness changes to go with color?  I guess I can see a reason if someone was colorblind, but when I zoom into an area, the thicker lines (like in targeted search) was overpowering.  This is more just an aesthetics issue for me and a curiosity if there was a reason." - Steve at SCTF.

**Comment by pjdohertygis** [comment]
Keep the colors and thickness varied, remove the arrow "caps" since they do not add value.

**Comment by jdokemaps** [comment]
Removed caps on NAPSG Sandbox.

**Comment by afackler** [comment]
Removed caps on IAFC.
