### ISSUE TITLE
Enhancement: The symbology chart / data dictionary needs to be fixed

### ISSUE THREAD

**Issue by pjdohertygis** [pjdohertygis/SARandFirstResponderSurvey#6]
https://www.arcgis.com/home/item.html?id=7a3371cd98224827b51e4f17205d6276 
-  Confirmed victim has the wrong symbol
![image](https://user-images.githubusercontent.com/4256979/62715264-007e3100-b9b5-11e9-9c07-6a9c73ac4c0c.png)

**Comment by pjdohertygis** [comment]
There may also be an issue with filename case - see notes from @tedrick to @jdokemaps

**Comment by jdokemaps** [comment]
The symbol has been fixed and the text case in the file name has been fixed as well, so it should show up on iOS devices now. The only thing I am concerned about is the size and legibility of the png file in the instructions.
