### ISSUE TITLE
Enhancement: Required Fields for Team Name, Your Name, and Search Type

### ISSUE THREAD

**Issue by pjdohertygis** [pjdohertygis/SARandFirstResponderSurvey#9]
All set, thank you. As far as the filling in of the task force names. Can we make the following a “Required Field”:
• Team Name
• Your Name
• Search Type

This along with the already required field of waypoint will give good filter options. Your thoughts sir?

Harris Henbest
District Chief
Port Everglades Command
Broward Sheriff's Fire Rescue & Emergency Services Dept.
1901 Eller Dr.
Fort Lauderdale, Florida 33316
Tel: 954-765-5372
Cell: 954-551-4280
Harris_Henbest@sheriff.org

**Comment by pjdohertygis** [comment]
Here is a video I made with instructions on how to download the latest version of a Survey https://www.youtube.com/watch?v=vCtenpj9QqA&feature=youtu.be&hd=1

**Comment by jdokemaps** [comment]
I made Team Name, Squad Leader, Your Name, and Search Type all required fields.

![image](https://user-images.githubusercontent.com/52461518/70275906-5947b580-176c-11ea-9a08-03f395e129ba.png)
